#ifndef GTF_EXPORT_ASPECTS_LANGUAGES_H
#define GTF_EXPORT_ASPECTS_LANGUAGES_H

//! @brief Language: Standard
#define GTF_LANGUAGE_Standard "240c88e6-7a07-4caf-ae8b-5f89620fb630"

#endif //GTF_EXPORT_ASPECTS_LANGUAGES_H
