#ifndef GTF_INCLUDED_LOCAL_EVENTS_IDENTIFIERS_H
#define GTF_INCLUDED_LOCAL_EVENTS_IDENTIFIERS_H

#include "group_Default.h"
#include "group_Application.h"

#endif //GTF_INCLUDED_LOCAL_EVENTS_IDENTIFIERS_H
