#ifndef GTF_EXPORT_ASPECTS_LANGUAGES_H
#define GTF_EXPORT_ASPECTS_LANGUAGES_H

//! @brief Language: Standard
#define GTF_LANGUAGE_Standard "91cca09e-7dd5-4aa3-98ea-a6ee15645053"

#endif //GTF_EXPORT_ASPECTS_LANGUAGES_H
