SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 2.6)
SET(X86_64 1)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

set(EB_PLATFORM_OS_FAMILY POSIX)
set(EB_PLATFORM_OS Linux)
set(EB_PLATFORM_ARCH x86_64)

MESSAGE(STATUS "Compiling for Linux x86-64")

SET(CMAKE_CXX_FLAGS "-m64 -mtune=generic -mfpmath=sse -msse -pthread")
SET(CMAKE_C_FLAGS "-m64 -mtune=generic -mfpmath=sse -msse -pthread")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,-Bsymbolic")
set(CMAKE_MODULE_LINKER_FLAGS "-Wl,-Bsymbolic")
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,-Bsymbolic")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
